// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD2TSZa-RoPUcuyujnhgdWQ9e-4aJwjl4',
    appId: '1:605400700319:web:8496a71939ccd68b9cd9aa',
    messagingSenderId: '605400700319',
    projectId: 'tiktok-clone-mj98',
    authDomain: 'tiktok-clone-mj98.firebaseapp.com',
    storageBucket: 'tiktok-clone-mj98.appspot.com',
    measurementId: 'G-PCEEBHR68D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbJ9BlPWZzXl8Chvrvr6-SwoG329QEMUU',
    appId: '1:605400700319:android:8d555c74b8ffc9a99cd9aa',
    messagingSenderId: '605400700319',
    projectId: 'tiktok-clone-mj98',
    storageBucket: 'tiktok-clone-mj98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVg2HH_vGVa7ZCZX6im1zacyP_Bip-T4w',
    appId: '1:605400700319:ios:658e2e39afee5cd99cd9aa',
    messagingSenderId: '605400700319',
    projectId: 'tiktok-clone-mj98',
    storageBucket: 'tiktok-clone-mj98.appspot.com',
    androidClientId: '605400700319-qjb9tknihb8b5gice1nvg673ajismb0k.apps.googleusercontent.com',
    iosClientId: '605400700319-65ecgt7tq5ekigovriogn6p4k0a19i5q.apps.googleusercontent.com',
    iosBundleId: 'com.example.tictokCloneFlutter',
  );
}
